export default function Head() {
  return (
    <>
      <title>portofolio</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="https://cdn-icons-png.flaticon.com/512/518/518713.png" />
    </>
  )
}
